package com.marshall.singlestonedemo.contacts.persistence.repository;

import java.util.List;

import org.mapstruct.Mapper;

import com.marshall.singlestonedemo.contacts.modeling.Contact;
import com.marshall.singlestonedemo.contacts.persistence.entity.ContactEntity;

/**
 * Utility to convert between the model and persistence representations of 
 * a Contact
 * 
 * The implementation for this class is generated by mapstruct and placed
 * into the target/generated-sources directory.
 *
 */
@Mapper(componentModel = "spring")
public interface ContactEntityMapper {

	public Contact entityToModel(ContactEntity entity);
	public List<Contact> entitiesToModels(List<ContactEntity> entities);
	
	public ContactEntity modelToEntity(Contact model);
	public List<ContactEntity> modelsToEntities(List<Contact> models);
}
