package com.marshall.singlestonedemo.contacts.persistence.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.marshall.singlestonedemo.contacts.persistence.entity.ContactEntity;

/**
 * A service that provides access to many CRUD operations to do with Contacts
 * 
 * The implementation for this is autogenerated by spring. See the JpaRepository
 * interface for details of provided methods.
 *
 */
@Repository
public interface ContactJPARepository extends JpaRepository<ContactEntity, Long>{

}
 